'use strict';

const categories = [
    {
        slug: 'kitchen',
        title: 'Kitchen Utensils',
        products: [
            { name: 'Stainless Steel Whisk',    price: 129,  img: 'img/kitchen-01.jpg' },
            { name: 'Non-Stick Frying Pan',     price: 549,  img: 'img/kitchen-02.jpg' },
            { name: 'Silicone Spatula Set',     price: 199,  img: 'img/kitchen-03.jpg' },
            { name: 'Ceramic Mixing Bowl',      price: 249,  img: 'img/kitchen-04.jpg' },
            { name: "Chef's Knife 8 inch",      price: 899,  img: 'img/kitchen-05.jpg' },
            { name: 'Wooden Cutting Board',     price: 329,  img: 'img/kitchen-06.jpg' },
            { name: 'Digital Kitchen Scale',    price: 749,  img: 'img/kitchen-07.jpg' },
            { name: 'Thermos Flask 1L',         price: 469,  img: 'img/kitchen-08.jpg' },
            { name: 'Garlic Press',             price: 149,  img: 'img/kitchen-09.jpg' },
            { name: 'Measuring Cup Set',        price: 179,  img: 'img/kitchen-10.jpg' },
            { name: 'Wooden Rolling Pin',       price: 219,  img: 'img/kitchen-11.jpg' },
            { name: 'Bamboo Colander',          price: 159,  img: 'img/kitchen-12.jpg' },
            { name: 'Cast Iron Skillet',        price: 799,  img: 'img/kitchen-13.jpg' },
            { name: 'Electric Kettle',          price: 1199, img: 'img/kitchen-14.jpg' },
            { name: 'Serving Tongs Set',        price: 139,  img: 'img/kitchen-15.jpg' },
            { name: 'Glass Food Containers',    price: 369,  img: 'img/kitchen-16.jpg' },
            { name: 'Mortar & Pestle',          price: 289,  img: 'img/kitchen-17.jpg' },
            { name: 'Dish Drying Rack',         price: 429,  img: 'img/kitchen-18.jpg' },
            { name: 'Rice Cooker 2L',           price: 1499, img: 'img/kitchen-19.jpg' },
            { name: 'Paring Knife Set',         price: 259,  img: 'img/kitchen-20.jpg' },
        ],
    },
    {
        slug: 'bags',
        title: 'Local Bags',
        products: [
            { name: 'Abaca Market Tote',       price: 499,  img: 'img/bags-01.jpg' },
            { name: 'Buri Beach Bag',          price: 399,  img: 'img/bags-02.jpg' },
            { name: 'Rattan Handbag',          price: 799,  img: 'img/bags-03.jpg' },
            { name: 'Bayong Banig Tote',       price: 329,  img: 'img/bags-04.jpg' },
            { name: 'Crocheted Shoulder Bag',  price: 449,  img: 'img/bags-05.jpg' },
            { name: 'Leather Sling Bag',       price: 1199, img: 'img/bags-06.jpg' },
            { name: 'Denim Bucket Bag',        price: 649,  img: 'img/bags-07.jpg' },
            { name: 'Canvas Drawstring Sack',  price: 299,  img: 'img/bags-08.jpg' },
            { name: 'Woven Laptop Bag',        price: 899,  img: 'img/bags-09.jpg' },
            { name: 'Kapis Evening Clutch',    price: 599,  img: 'img/bags-10.jpg' },
            { name: 'Nipa Palm Mini Bag',      price: 359,  img: 'img/bags-11.jpg' },
            { name: 'Rattan Backpack',         price: 999,  img: 'img/bags-12.jpg' },
            { name: 'Beaded Evening Bag',      price: 759,  img: 'img/bags-13.jpg' },
            { name: 'Banig Duffel Bag',        price: 1099, img: 'img/bags-14.jpg' },
            { name: 'Nito Wall Clutch',        price: 499,  img: 'img/bags-15.jpg' },
            { name: 'Abaca Hobo Bag',          price: 899,  img: 'img/bags-16.jpg' },
            { name: 'Buri Straw Hat',          price: 299,  img: 'img/bags-17.jpg' },
            { name: 'Coconut Shell Purse',     price: 549,  img: 'img/bags-18.jpg' },
            { name: 'Boho Fringe Tote',        price: 649,  img: 'img/bags-19.jpg' },
            { name: 'Rattan Lunch Basket',     price: 399,  img: 'img/bags-20.jpg' },
        ],
    },
    {
        slug: 'perfumes',
        title: 'Perfumes',
        products: [
            { name: 'Sampaguita Bloom EDP',    price: 699,  img: 'img/perfumes-01.jpg' },
            { name: 'Ylang-Ylang Night EDP',   price: 649,  img: 'img/perfumes-02.jpg' },
            { name: 'Calamansi Breeze EDT',    price: 549,  img: 'img/perfumes-03.jpg' },
            { name: 'Coconut Sunset EDT',      price: 599,  img: 'img/perfumes-04.jpg' },
            { name: 'Jasmine Silk EDP',        price: 749,  img: 'img/perfumes-05.jpg' },
            { name: 'Sandalwood Oud',          price: 999,  img: 'img/perfumes-06.jpg' },
            { name: 'Vanilla Amber EDP',       price: 799,  img: 'img/perfumes-07.jpg' },
            { name: 'Citrus Verde EDT',        price: 499,  img: 'img/perfumes-08.jpg' },
            { name: 'Frangipani Paradise',     price: 849,  img: 'img/perfumes-09.jpg' },
            { name: 'Tea Leaf Musk',           price: 699,  img: 'img/perfumes-10.jpg' },
            { name: 'Sea Salt & Driftwood',    price: 749,  img: 'img/perfumes-11.jpg' },
            { name: 'Sweet Pandan EDP',        price: 569,  img: 'img/perfumes-12.jpg' },
            { name: 'Pink Sugar EDP',          price: 899,  img: 'img/perfumes-13.jpg' },
            { name: 'Amber Musk EDT',          price: 799,  img: 'img/perfumes-14.jpg' },
            { name: 'Cherry Blossom EDT',      price: 749,  img: 'img/perfumes-15.jpg' },
            { name: 'Lime Zest EDT',           price: 529,  img: 'img/perfumes-16.jpg' },
            { name: 'Oud & Rose EDP',          price: 1199, img: 'img/perfumes-17.jpg' },
            { name: 'Vanilla Clouds EDT',      price: 649,  img: 'img/perfumes-18.jpg' },
            { name: 'Aqua Marine EDT',         price: 699,  img: 'img/perfumes-19.jpg' },
            { name: 'Midnight Leather EDT',    price: 999,  img: 'img/perfumes-20.jpg' },
        ],
    },
    {
        slug: 'lights',
        title: 'Lights',
        products: [
            { name: 'Bamboo Desk Lamp',         price: 549,  img: 'img/lights-01.jpg' },
            { name: 'Rattan Pendant Globe',     price: 799,  img: 'img/lights-02.jpg' },
            { name: 'LED Mosquito Lamp',        price: 349,  img: 'img/lights-03.jpg' },
            { name: 'Capiz Chandelier',         price: 2999, img: 'img/lights-04.jpg' },
            { name: 'Lantern Nightlight',       price: 199,  img: 'img/lights-05.jpg' },
            { name: 'Capsule Hanging Lamp',     price: 449,  img: 'img/lights-06.jpg' },
            { name: 'Sputnik Bulb Fixture',     price: 649,  img: 'img/lights-07.jpg' },
            { name: 'Fairy String Lights',      price: 259,  img: 'img/lights-08.jpg' },
            { name: 'Bamboo Floor Lamp',        price: 1299, img: 'img/lights-09.jpg' },
            { name: 'Vintage Edison Bulb',      price: 99,   img: 'img/lights-10.jpg' },
            { name: 'Clamp Reading Lamp',       price: 509,  img: 'img/lights-11.jpg' },
            { name: 'Smart Color Bulb',         price: 459,  img: 'img/lights-12.jpg' },
            { name: 'Neon Sign Lamp',           price: 899,  img: 'img/lights-13.jpg' },
            { name: 'Paper Lantern Set',        price: 259,  img: 'img/lights-14.jpg' },
            { name: 'Brass Ceiling Pendant',    price: 1299, img: 'img/lights-15.jpg' },
            { name: 'Star Nightlight',          price: 349,  img: 'img/lights-16.jpg' },
            { name: 'Track Light Bar',          price: 1099, img: 'img/lights-17.jpg' },
            { name: 'Tiffany Stained Lamp',     price: 2499, img: 'img/lights-18.jpg' },
            { name: 'Wall Sconce',              price: 699,  img: 'img/lights-19.jpg' },
            { name: 'Solar Garden Light',       price: 459,  img: 'img/lights-20.jpg' },
        ],
    },
    {
        slug: 'shoes',
        title: 'Shoes',
        products: [
            { name: 'Marikina Leather Loafers',   price: 1499, img: 'img/shoes-01.jpg' },
            { name: 'Canvas Slip-Ons',            price: 699,  img: 'img/shoes-02.jpg' },
            { name: 'Running Sneakers',           price: 1599, img: 'img/shoes-03.jpg' },
            { name: 'Rubber Rain Boots',          price: 899,  img: 'img/shoes-04.jpg' },
            { name: 'Espadrille Sandals',         price: 549,  img: 'img/shoes-05.jpg' },
            { name: 'Basketball High-Tops',       price: 1799, img: 'img/shoes-06.jpg' },
            { name: 'Bakyâ Blend Slippers',       price: 249,  img: 'img/shoes-07.jpg' },
            { name: 'Ballet Flats',               price: 899,  img: 'img/shoes-08.jpg' },
            { name: 'Trail Hiking Boots',         price: 2199, img: 'img/shoes-09.jpg' },
            { name: 'Court Dress Shoes',          price: 1299, img: 'img/shoes-10.jpg' },
            { name: 'Wheeler Work Boots 6"',      price: 1899, img: 'img/shoes-11.jpg' },
            { name: 'Breathable Mesh Runners',    price: 1399, img: 'img/shoes-12.jpg' },
            { name: 'Slip-Resistant Service Shoes', price: 799, img: 'img/shoes-13.jpg' },
            { name: 'Knit Jogger Sneakers',       price: 999,  img: 'img/shoes-14.jpg' },
            { name: 'Boat Deck Shoes',            price: 1099, img: 'img/shoes-15.jpg' },
            { name: 'Combat Boots',               price: 1699, img: 'img/shoes-16.jpg' },
            { name: 'Platform Sandals',           price: 749,  img: 'img/shoes-17.jpg' },
            { name: 'Wingtip Oxfords',            price: 2099, img: 'img/shoes-18.jpg' },
            { name: "Kids' Velcro Runners",       price: 549,  img: 'img/shoes-19.jpg' },
            { name: 'Road Cycling Shoes',         price: 1299, img: 'img/shoes-20.jpg' },
        ],
    },
];

module.exports = { categories };